name: React & and Publish

on:
  push:
    branches:
      - main

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install necessary packages
        run: pnpm install

      - name: Build the packages
        run: pnpm turbo run build --filter=@pxr/core --filter=@pxr/db --filter=@pxr/cli

      - name: Changeset Releases
        uses: changesets/action@v1
        with:
          publish: pnpm run pkg:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
